# Amazon S3 configure
AMAZON_STORAGE = {
    'ACCESS_KEY' : "AKIAIMPLN6YTZVD5Q3TA",
    'SECRET_KEY' : "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",
    'BUCKET_NAME' : 'abome-test',
    'MAX_SIZE' : 1024*1024*1024*2
}

#third auth configure
#twitter
SOCIAL_AUTH_TWITTER_KEY = ''
SOCIAL_AUTH_TWITTER_SECRET = ''
#facebook
SOCIAL_AUTH_FACEBOOK_KEY = ''
SOCIAL_AUTH_FACEBOOK_SECRET = ''
SOCIAL_AUTH_FACEBOOK_SCOPE = ['']
#SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {}